sudo: false
language: node_js
node_js:
  - '5'

before_install:
  - rvm install 2.3.1
  - gem update --system
  - gem install sass
  - gem install compass

install:
  - mkdir -p coverage
  - npm install

script:
  - npm run build
  - npm run review
  - npm run test

after_script:
  - "node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- tests --recursive --reporter=xunit-file && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"

after_success:
  - rm app/public/.gitignore
  - git add . && git commit -a -m 'added public'
  - git push -f https://git.heroku.com/opentrials-ebola-tracker.git master