sudo: false
language: node_js
node_js:
  - '4.1'

before_install:
  - gem update --system
  - gem install sass

install:
  - npm install

script:
  - npm run build
 # - npm run review
  - npm run test

after_script:
  - node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

#after_success:
#  - rm app/public/.gitignore
#  - git add . && git commit -a -m 'added public'
#  - git push -f git@heroku.com:opentrials-ebola-tracker.git master