sudo: false
language: node_js
node_js:
  - '5'

addons:
  ssh_known_hosts:
  - heroku.com

before_install:
  - rvm install 2.3.1
  - gem update --system
  - gem install sass
  - gem install compass

install:
  - mkdir -p coverage
  - npm install

#before_script:
#  - echo -e "Host heroku.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - npm run build
  - npm run review
  - npm run test

after_script:
  - "node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- tests --recursive --reporter=xunit-file && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"

#after_success:
#  - rm app/public/.gitignore
#  - git add . && git commit -a -m 'added public'
#  - git push -f git@heroku.com:opentrials-ebola-tracker.git master

before_deploy:
  - rm app/public/.gitignore

deploy:
  provider: heroku
  app: opentrials-ebola-tracker
  api_key: 54632a2c-2498-4655-88af-19a0f233c4c7
  skip_cleanup: true
  on: master