sudo: false
language: node_js
node_js:
  - '6'

addons:
  ssh_known_hosts:
  - heroku.com

before_install:
  - rvm install 2.3.1
  - gem update --system
  - gem install sass
  - gem install compass

install:
  - mkdir -p coverage
  - npm install

script:
  - npm run build
  - npm run review
  - npm run test

after_script:
  - "node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- tests --recursive --reporter=xunit-file && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"

before_deploy:
  - rm app/public/.gitignore
  - git config user.email "you@example.com"
  - git config user.name "Your Name"
  - git add --all .
  - git commit -a -m 'added public'

# deploy:
  # provider: heroku
  # app: opentrials-ebola-tracker
  # api_key: 54632a2c-2498-4655-88af-19a0f233c4c7
  # skip_cleanup: true
  # on: master
